services:
  - type: web
    name: socket-service
    env: node
    rootDir: AlgoCode-Socket-Service
    buildCommand: npm install
    startCommand: npm start
    
  - type: web
    name: submission-service
    env: node
    rootDir: AlgoCode-Submission-Service
    buildCommand: npm install
    startCommand: npm start

  - type: web
    name: problem-service
    env: node
    rootDir: Algocode-Problem-Service
    buildCommand: npm install
    startCommand: npm start

  - type: web
    name: user-service
    env: node
    rootDir: Algocode-User-Service
    buildCommand: npm install
    startCommand: npm start
